fix(crawler): add retry mechanism in case of ConnectionError (#121)
Some ubuntu crawlings may sometimes fail with the following error:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

add a retry mechanism leveraging tenacity to prevent this
kind of transient failures from causing the whole
process to bail out entirely.