chore(rhel): suppress legacy_ebpf on RHEL8.9 kernels
RHEL8.9 kernels backported a change from kernel 6.15 which
causes:

In file included from /code/sysdig-rw/bpf/probe.c:26:
 /code/sysdig-rw/bpf/fillers.h:1822:19: error: no member named 'parent' in 'struct kernfs_node'; did you mean '__parent'?
                         kn = _READ(kn->parent);
                                        ^~~~~~
                                        __parent