[SMAGENT-5086] replace download-ib01.fedoraproject.org with mirrors.rit.edu (#101)
Recent fedora crawls have been failing due to

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://download-ib01.fedoraproject.org/pub/fedora/linux/releases/

Suggesting that mirror download-ib01.fedoraproject.net might have been taken down.

Until we implament a proper mechanism with metaliknk,
replace it with another one, like mirrors.rit.edu.