disable driver creation for kernel 6.11 (#144)
* disable driver creation for kernel 6.11

Ubuntu noble started featuring kernel 6.11.0-1001-oem which
has the following issues:

a) legacy eBPF

In file included from /code/sysdig-rw/bpf/probe.c:27:
/code/sysdig-rw/bpf/fillers.h:2871:22: error: no member named '__i_ctime' in 'struct inode'
        time = _READ(inode->__i_ctime);
                     ~~~~~  ^
/code/sysdig-rw/bpf/plumbing_helpers.h:22:51: note: expanded from macro '_READ'
                    bpf_probe_read_kernel(&_val, sizeof(_val), &P);     \

which then causes other cascading errors
Notice how as today, this issue has not been fixed

b) kmod

/code/sysdig-rw/main.c: In function 'drop_nostate_event':
/code/sysdig-rw/main.c:1660:22: error: implicit declaration of function 'fd_is_open'; did you mean 'finish_open'? [-Werror=implicit-function-declaration]
 1660 |                     !fd_is_open(close_fd, fdt)
      |                      ^~~~~~~~~~
      |                      finish_open

This issue has been fixed starting with 13.3.2.

* group 6.11 together with 6.10