fix crawling bug introduced by distro filtering (#94)
With #68 we added support for distro filtering but a small
bug slipped through the crack causing the following error
when using the crawling operation:

  File "/builder/probe_builder/__init__.py", line 203, in crawl
    kernels = crawl_kernels(distro, distro_filter, crawler_filter=crawler_filter)
TypeError: crawl_kernels() got multiple values for argument 'crawler_filter'

Fix it.